#ifndef BZH_ANK_SE_CODE_DEFINE_ITEM_H
#define BZH_ANK_SE_CODE_DEFINE_ITEM_H

#include "mainwindow.h"

QList<quint16> list_code_item_props_normal;
QList<quint16> list_code_item_props_cooking;

QList<quint16> list_code_item_equipment_weapon_generic;
QList<quint16> list_code_item_equipment_weapon_Lloyd;
QList<quint16> list_code_item_equipment_weapon_Elie;
QList<quint16> list_code_item_equipment_weapon_Tio;
QList<quint16> list_code_item_equipment_weapon_Randy;
QList<quint16> list_code_item_equipment_weapon_Lazy;
QList<quint16> list_code_item_equipment_weapon_Noel;
QList<quint16> list_code_item_equipment_weapon_Rixia;
QList<quint16> list_code_item_equipment_weapon_Dudley;
QList<quint16> list_code_item_equipment_weapon_Arios;
QList<quint16> list_code_item_equipment_weapon_Zeit;

QList<quint16> list_code_item_equipment_clothes;
QList<quint16> list_code_item_equipment_shoes;
QList<quint16> list_code_item_equipment_jewelry;

QList<quint16> list_code_item_circuit_normal;
QList<quint16> list_code_item_circuit_core;
QList<quint16> list_code_item_circuit_debug;

QList<quint16> list_code_item_event_story;
QList<quint16> list_code_item_event_furnishing;
QList<quint16> list_code_item_event_car;

QList<quint16> list_code_item_food;
QList<quint16> list_code_item_book;

QList<quint16> list_code_item_fishing_bait;
QList<quint16> list_code_item_fishing_fish;
QList<quint16> list_code_item_fishing_rod;

void setup_list_code_items()
{
    //回复药
    list_code_item_props_normal.append(0x01f4);
    //中回复药
    list_code_item_props_normal.append(0x01f5);
    //大回复药
    list_code_item_props_normal.append(0x01f6);
    //全回复药
    list_code_item_props_normal.append(0x01f7);
    //EP填充剂I
    list_code_item_props_normal.append(0x01f8);
    //EP填充剂II
    list_code_item_props_normal.append(0x01f9);
    //EP填充剂III
    list_code_item_props_normal.append(0x01fa);
    //复苏药
    list_code_item_props_normal.append(0x01fb);
    //圣灵药
    list_code_item_props_normal.append(0x01fc);
    //圣灵药·改
    list_code_item_props_normal.append(0x01fd);
    //还魂粉
    list_code_item_props_normal.append(0x01fe);
    //还魂胶囊
    list_code_item_props_normal.append(0x01ff);
    //解毒药
    list_code_item_props_normal.append(0x0200);
    //软化膏
    list_code_item_props_normal.append(0x0201);
    //绝缘胶带
    list_code_item_props_normal.append(0x0202);
    //解冻暖炉
    list_code_item_props_normal.append(0x0203);
    //舒缓凝胶
    list_code_item_props_normal.append(0x0204);
    //冷却喷雾
    list_code_item_props_normal.append(0x0205);
    //眼药
    list_code_item_props_normal.append(0x0206);
    //提神薄荷
    list_code_item_props_normal.append(0x0207);
    //苏醒药
    list_code_item_props_normal.append(0x0208);
    //镇静剂
    list_code_item_props_normal.append(0x0209);
    //S-药片
    list_code_item_props_normal.append(0x020a);
    //痊愈之药
    list_code_item_props_normal.append(0x020b);
    //爆灵宝玉
    list_code_item_props_normal.append(0x020c);
    //烟雾弹
    list_code_item_props_normal.append(0x020d);
    //战斗探测器
    list_code_item_props_normal.append(0x020e);
    //枫糖蛋糕
    list_code_item_props_normal.append(0x020f);
    //赏月面包
    list_code_item_props_normal.append(0x0210);
    //奶油菠萝包
    list_code_item_props_normal.append(0x0211);
    //贝奈特绝品
    list_code_item_props_normal.append(0x0212);
    //极厚猪排三明治
    list_code_item_props_normal.append(0x0213);
    //最终旅途
    list_code_item_props_normal.append(0x0214);
    //咪西包子
    list_code_item_props_normal.append(0x0216);
    //咪雪丸子
    list_code_item_props_normal.append(0x0217);
    //罐装果汁
    list_code_item_props_normal.append(0x0218);
    //罐装咖啡
    list_code_item_props_normal.append(0x0219);
    //强壮苦番茄猪骨汤
    list_code_item_props_normal.append(0x021a);
    //暖心猪骨汤
    list_code_item_props_normal.append(0x021b);
    //运动汽水X
    list_code_item_props_normal.append(0x021c);
    //苦西红柿苏打
    list_code_item_props_normal.append(0x021d);

    //天上面[日轮]
    list_code_item_props_cooking.append(0x0190);
    //微苦担担面
    list_code_item_props_cooking.append(0x0191);
    //极苦面[断头]
    list_code_item_props_cooking.append(0x0192);
    //神仙麻婆[麒麟]
    list_code_item_props_cooking.append(0x0193);
    //药膳麻婆豆腐
    list_code_item_props_cooking.append(0x0194);
    //炼狱麻婆[阎魔]
    list_code_item_props_cooking.append(0x0195);
    //天下一品炒饭
    list_code_item_props_cooking.append(0x0196);
    //龙老炒饭
    list_code_item_props_cooking.append(0x0197);
    //杂色锅巴饭
    list_code_item_props_cooking.append(0x0198);
    //极品牛排[刚]
    list_code_item_props_cooking.append(0x0199);
    //精力牛排
    list_code_item_props_cooking.append(0x019A);
    //顽固肉排[岩]
    list_code_item_props_cooking.append(0x019B);
    //三日久煮炖菜
    list_code_item_props_cooking.append(0x019C);
    //久煮炖菜
    list_code_item_props_cooking.append(0x019D);
    //混沌久煮[浊]
    list_code_item_props_cooking.append(0x019E);
    //大地锅[烂漫]
    list_code_item_props_cooking.append(0x019F);
    //大饱口福锅
    list_code_item_props_cooking.append(0x01A0);
    //男人料理[山]
    list_code_item_props_cooking.append(0x01A1);
    //天河锅[瑞云]
    list_code_item_props_cooking.append(0x01A2);
    //芳醇潮锅
    list_code_item_props_cooking.append(0x01A3);
    //男人料理[川]
    list_code_item_props_cooking.append(0x01A4);
    //特快炸鱼[疾]
    list_code_item_props_cooking.append(0x01A5);
    //炸鱼排
    list_code_item_props_cooking.append(0x01A6);
    //箭之鱼
    list_code_item_props_cooking.append(0x01A7);
    //丰盛蛋包饭
    list_code_item_props_cooking.append(0x01A8);
    //大师蛋包饭
    list_code_item_props_cooking.append(0x01A9);
    //激辣炸弹蛋包饭
    list_code_item_props_cooking.append(0x01AA);
    //翠玉面[治愈]
    list_code_item_props_cooking.append(0x01AB);
    //香草面
    list_code_item_props_cooking.append(0x01AC);
    //细针面
    list_code_item_props_cooking.append(0x01AD);
    //双层汉堡
    list_code_item_props_cooking.append(0x01AE);
    //午餐汉堡
    list_code_item_props_cooking.append(0x01AF);
    //苦味汉堡
    list_code_item_props_cooking.append(0x01B0);
    //四味奶酪比萨
    list_code_item_props_cooking.append(0x01B1);
    //热酪比萨
    list_code_item_props_cooking.append(0x01B2);
    //四重番茄比萨
    list_code_item_props_cooking.append(0x01B3);
    //强效三明治
    list_code_item_props_cooking.append(0x01B4);
    //鲜美三明治
    list_code_item_props_cooking.append(0x01B5);
    //守护三明治
    list_code_item_props_cooking.append(0x01B6);
    //真心饭盒[诚]
    list_code_item_props_cooking.append(0x01B7);
    //行乐午餐饭盒
    list_code_item_props_cooking.append(0x01B8);
    //不可思议盒饭[仰天]
    list_code_item_props_cooking.append(0x01B9);
    //辉煌汤
    list_code_item_props_cooking.append(0x01BA);
    //奶油浓汤
    list_code_item_props_cooking.append(0x01BB);
    //奇妙汤
    list_code_item_props_cooking.append(0x01BC);
    //奇幻糖果
    list_code_item_props_cooking.append(0x01BD);
    //七色棉花糖
    list_code_item_props_cooking.append(0x01BE);
    //秘密棉花糖
    list_code_item_props_cooking.append(0x01BF);
    //天上甜点[夜月]
    list_code_item_props_cooking.append(0x01C0);
    //香甜巧克力蛋糕
    list_code_item_props_cooking.append(0x01C1);
    //反射巧克力蛋糕
    list_code_item_props_cooking.append(0x01C2);
    //宝物甜点[白雪]
    list_code_item_props_cooking.append(0x01C3);
    //溜滑杏仁豆腐
    list_code_item_props_cooking.append(0x01C4);
    //爽弹布丁
    list_code_item_props_cooking.append(0x01C5);
    //冰凉甜点[七彩]
    list_code_item_props_cooking.append(0x01C6);
    //混合冰激凌
    list_code_item_props_cooking.append(0x01C7);
    //痊愈冰激凌
    list_code_item_props_cooking.append(0x01C8);
    //绝品甜点[瞬动]
    list_code_item_props_cooking.append(0x01C9);
    //轻快爆米花
    list_code_item_props_cooking.append(0x01CA);
    //隐秘爆米花
    list_code_item_props_cooking.append(0x01CB);
    //玉露[绿风]
    list_code_item_props_cooking.append(0x01CC);
    //考究抹茶拿铁
    list_code_item_props_cooking.append(0x01CD);
    //良药[熊竹]
    list_code_item_props_cooking.append(0x01CE);
    //甘露[紫绀]
    list_code_item_props_cooking.append(0x01CF);
    //铃铛草莓果汁
    list_code_item_props_cooking.append(0x01D0);
    //紫色液体
    list_code_item_props_cooking.append(0x01D1);
    //黑茶[梦魇杀手]
    list_code_item_props_cooking.append(0x01D2);
    //浓厚卡布奇诺
    list_code_item_props_cooking.append(0x01D3);
    //褐色液体
    list_code_item_props_cooking.append(0x01D4);
    //秘水[桃源乡]
    list_code_item_props_cooking.append(0x01D5);
    //桃色紫薇
    list_code_item_props_cooking.append(0x01D6);
    //粉红液体
    list_code_item_props_cooking.append(0x01D7);
    //失败作[引以为戒]
    list_code_item_props_cooking.append(0x01D8);
    //猫食
    list_code_item_props_cooking.append(0x01D9);


    //练习用武器
    list_code_item_equipment_weapon_generic.append(0x0009);

    //强力破坏者·改
    list_code_item_equipment_weapon_Lloyd.append(0x03E8);
    //双钉棍
    list_code_item_equipment_weapon_Lloyd.append(0x03E9);
    //螺纹双棍
    list_code_item_equipment_weapon_Lloyd.append(0x03EA);
    //罪恶制裁者
    list_code_item_equipment_weapon_Lloyd.append(0x03EB);
    //集团破坏者
    list_code_item_equipment_weapon_Lloyd.append(0x03EC);
    //猛虎棍
    list_code_item_equipment_weapon_Lloyd.append(0x03ED);
    //玄象棍
    list_code_item_equipment_weapon_Lloyd.append(0x03EE);
    //钢管旋棍
    list_code_item_equipment_weapon_Lloyd.append(0x03F6);
    //捕捉者
    list_code_item_equipment_weapon_Lloyd.append(0x03EF);
    //裂地棍
    list_code_item_equipment_weapon_Lloyd.append(0x03F0);
    //神圣五芒星
    list_code_item_equipment_weapon_Lloyd.append(0x03F1);
    //七星击
    list_code_item_equipment_weapon_Lloyd.append(0x03F2);
    //零·破坏者
    list_code_item_equipment_weapon_Lloyd.append(0x03F3);
    //雷神之佑
    list_code_item_equipment_weapon_Lloyd.append(0x03F4);
    //无限之光
    list_code_item_equipment_weapon_Lloyd.append(0x03F5);

    //倾国
    list_code_item_equipment_weapon_Elie.append(0x03FD);
    //喜悦
    list_code_item_equipment_weapon_Elie.append(0x03FE);
    //红色樱草II
    list_code_item_equipment_weapon_Elie.append(0x03FF);
    //丝绒之吻
    list_code_item_equipment_weapon_Elie.append(0x0400);
    //纯真女皇
    list_code_item_equipment_weapon_Elie.append(0x0401);
    //高洁圣女
    list_code_item_equipment_weapon_Elie.append(0x0402);
    //银色密雨
    list_code_item_equipment_weapon_Elie.append(0x0403);
    //神恩
    list_code_item_equipment_weapon_Elie.append(0x0404);
    //暗灰小丑
    list_code_item_equipment_weapon_Elie.append(0x0405);
    //千金·烙印
    list_code_item_equipment_weapon_Elie.append(0x0406);
    //血色光辉
    list_code_item_equipment_weapon_Elie.append(0x0407);
    //纯白圣枪
    list_code_item_equipment_weapon_Elie.append(0x0408);
    //能天使威光
    list_code_item_equipment_weapon_Elie.append(0x0409);

    //探索者
    list_code_item_equipment_weapon_Tio.append(0x0413);
    //聚魔杖
    list_code_item_equipment_weapon_Tio.append(0x0414);
    //高纯能量
    list_code_item_equipment_weapon_Tio.append(0x0415);
    //光辉之翼
    list_code_item_equipment_weapon_Tio.append(0x0416);
    //精神同步
    list_code_item_equipment_weapon_Tio.append(0x0417);
    //魔导加速器
    list_code_item_equipment_weapon_Tio.append(0x0418);
    //先导者
    list_code_item_equipment_weapon_Tio.append(0x0419);
    //黑暗搏动
    list_code_item_equipment_weapon_Tio.append(0x041A);
    //星之脉冲
    list_code_item_equipment_weapon_Tio.append(0x041B);
    //天启
    list_code_item_equipment_weapon_Tio.append(0x041C);
    //宇宙崩坏
    list_code_item_equipment_weapon_Tio.append(0x041D);

    //全力冲击
    list_code_item_equipment_weapon_Randy.append(0x0425);
    //格斗战斧
    list_code_item_equipment_weapon_Randy.append(0x0427);
    //巨象震慑者
    list_code_item_equipment_weapon_Randy.append(0x0428);
    //终结粉碎者
    list_code_item_equipment_weapon_Randy.append(0x0429);
    //高热蒸汽
    list_code_item_equipment_weapon_Randy.append(0x042A);
    //白银冲击枪
    list_code_item_equipment_weapon_Randy.append(0x042B);
    //黑暗制造者
    list_code_item_equipment_weapon_Randy.append(0x042C);
    //破坏神·改
    list_code_item_equipment_weapon_Randy.append(0x042D);
    //终极冲击
    list_code_item_equipment_weapon_Randy.append(0x042E);
    //邪恶粉碎者
    list_code_item_equipment_weapon_Randy.append(0x042F);
    //天灾
    list_code_item_equipment_weapon_Randy.append(0x0430);
    //屠龙深渊
    list_code_item_equipment_weapon_Randy.append(0x0431);

    //皮拳套
    list_code_item_equipment_weapon_Lazy.append(0x0439);
    //罪恶拳套
    list_code_item_equipment_weapon_Lazy.append(0x043A);
    //合金拳套
    list_code_item_equipment_weapon_Lazy.append(0x043B);
    //音速狂潮
    list_code_item_equipment_weapon_Lazy.append(0x043C);
    //螺旋冲击
    list_code_item_equipment_weapon_Lazy.append(0x043D);
    //漆黑螫刺
    list_code_item_equipment_weapon_Lazy.append(0x043E);
    //王者拳套
    list_code_item_equipment_weapon_Lazy.append(0x043F);
    //彗星拳套
    list_code_item_equipment_weapon_Lazy.append(0x0440);
    //范式谜爪
    list_code_item_equipment_weapon_Lazy.append(0x0441);
    //戒律护手
    list_code_item_equipment_weapon_Lazy.append(0x0442);
    //灵光护手
    list_code_item_equipment_weapon_Lazy.append(0x0443);
    //乐园
    list_code_item_equipment_weapon_Lazy.append(0x0444);
    //七耀圣腕
    list_code_item_equipment_weapon_Lazy.append(0x0445);

    //交叉火力
    list_code_item_equipment_weapon_Noel.append(0x044C);
    //岩石尘碎
    list_code_item_equipment_weapon_Noel.append(0x044D);
    //闪光甲虫
    list_code_item_equipment_weapon_Noel.append(0x044E);
    //圣十字
    list_code_item_equipment_weapon_Noel.append(0x044F);
    //野马
    list_code_item_equipment_weapon_Noel.append(0x0450);
    //M8公猫
    list_code_item_equipment_weapon_Noel.append(0x0451);
    //杀戮黄蜂
    list_code_item_equipment_weapon_Noel.append(0x0452);
    //三重风暴
    list_code_item_equipment_weapon_Noel.append(0x0453);
    //无畏之枪
    list_code_item_equipment_weapon_Noel.append(0x0454);
    //白隼
    list_code_item_equipment_weapon_Noel.append(0x0455);
    //第五爆裂枪
    list_code_item_equipment_weapon_Noel.append(0x0456);
    //挚爱恋人
    list_code_item_equipment_weapon_Noel.append(0x0457);
    //雷电魔枪
    list_code_item_equipment_weapon_Noel.append(0x0458);
    //日耀弧光
    list_code_item_equipment_weapon_Noel.append(0x0459);

    //八尺乌
    list_code_item_equipment_weapon_Rixia.append(0x0460);
    //黑鸫
    list_code_item_equipment_weapon_Rixia.append(0x0461);
    //降魔不知火
    list_code_item_equipment_weapon_Rixia.append(0x0462);
    //灵剑·奠邪
    list_code_item_equipment_weapon_Rixia.append(0x0463);
    //曳影之剑
    list_code_item_equipment_weapon_Rixia.append(0x0464);

    //皇帝
    list_code_item_equipment_weapon_Dudley.append(0x0465);
    //黑鹰
    list_code_item_equipment_weapon_Dudley.append(0x0466);
    //龙神
    list_code_item_equipment_weapon_Dudley.append(0x0467);
    //恶魔
    list_code_item_equipment_weapon_Dudley.append(0x0468);
    //制裁
    list_code_item_equipment_weapon_Dudley.append(0x0469);

    //利剑『隼风』
    list_code_item_equipment_weapon_Arios.append(0x046A);

    //亚麻拳套
    list_code_item_equipment_weapon_Zeit.append(0x046F);
    //尖钉项圈
    list_code_item_equipment_weapon_Zeit.append(0x0474);

    //皮革背带
    list_code_item_equipment_clothes.append(0x0477);
    //纤维夹克
    list_code_item_equipment_clothes.append(0x05DC);
    //强化牛仔服
    list_code_item_equipment_clothes.append(0x05DD);
    //弹性大衣
    list_code_item_equipment_clothes.append(0x05DE);
    //荆棘夹克
    list_code_item_equipment_clothes.append(0x05DF);
    //水珠连衣裙
    list_code_item_equipment_clothes.append(0x05E0);
    //机动战斗服
    list_code_item_equipment_clothes.append(0x05E1);
    //符文长袍
    list_code_item_equipment_clothes.append(0x05E2);
    //野战套装
    list_code_item_equipment_clothes.append(0x05E3);
    //向日葵斗篷
    list_code_item_equipment_clothes.append(0x05E4);
    //求生背心
    list_code_item_equipment_clothes.append(0x05E5);
    //牛仔皮衣
    list_code_item_equipment_clothes.append(0x05E6);
    //影丸外套
    list_code_item_equipment_clothes.append(0x05E7);
    //祭司法衣
    list_code_item_equipment_clothes.append(0x05E8);
    //军风大衣
    list_code_item_equipment_clothes.append(0x05E9);
    //龙华树之服
    list_code_item_equipment_clothes.append(0x05EA);
    //钛金铠甲
    list_code_item_equipment_clothes.append(0x05EB);
    //晚礼服
    list_code_item_equipment_clothes.append(0x05EC);
    //神圣法袍
    list_code_item_equipment_clothes.append(0x05ED);
    //邪恶胸甲
    list_code_item_equipment_clothes.append(0x05EE);
    //七龙装甲
    list_code_item_equipment_clothes.append(0x05EF);
    //星辰羽衣
    list_code_item_equipment_clothes.append(0x05F0);
    //暴风长袍
    list_code_item_equipment_clothes.append(0x05F1);
    //七耀神威圣铠
    list_code_item_equipment_clothes.append(0x05F2);
    //七耀极星圣衣
    list_code_item_equipment_clothes.append(0x05F3);
    //勇猛夹克
    list_code_item_equipment_clothes.append(0x05F4);
    //纯净礼裙
    list_code_item_equipment_clothes.append(0x05F5);
    //智慧斗篷
    list_code_item_equipment_clothes.append(0x05F6);
    //野性大衣
    list_code_item_equipment_clothes.append(0x05F7);
    //盟约法衣
    list_code_item_equipment_clothes.append(0x05F8);
    //增幅战斗装
    list_code_item_equipment_clothes.append(0x05F9);
    //规则西装
    list_code_item_equipment_clothes.append(0x05FA);
    //歼天幻舞装
    list_code_item_equipment_clothes.append(0x05FB);
    //动力服Z
    list_code_item_equipment_clothes.append(0x05FC);

    //护腿甲
    list_code_item_equipment_shoes.append(0x0478);
    //钉鞋
    list_code_item_equipment_shoes.append(0x0640);
    //远足鞋
    list_code_item_equipment_shoes.append(0x0641);
    //加速跑鞋
    list_code_item_equipment_shoes.append(0x0642);
    //田园鞋
    list_code_item_equipment_shoes.append(0x0643);
    //珐琅凉鞋
    list_code_item_equipment_shoes.append(0x0644);
    //军用靴
    list_code_item_equipment_shoes.append(0x0645);
    //弹簧跑鞋
    list_code_item_equipment_shoes.append(0x0646);
    //影丸雪踏
    list_code_item_equipment_shoes.append(0x0647);
    //白色帆布鞋
    list_code_item_equipment_shoes.append(0x0648);
    //斯托雷加越野鞋
    list_code_item_equipment_shoes.append(0x0649);
    //檀木树脂靴
    list_code_item_equipment_shoes.append(0x064A);
    //黑靴
    list_code_item_equipment_shoes.append(0x064B);
    //纤足高跟鞋
    list_code_item_equipment_shoes.append(0x064C);
    //军用作战靴
    list_code_item_equipment_shoes.append(0x064D);
    //骑士护腿
    list_code_item_equipment_shoes.append(0x064E);
    //都市皮鞋
    list_code_item_equipment_shoes.append(0x064F);
    //柔光凉鞋
    list_code_item_equipment_shoes.append(0x0650);
    //金属强化鞋
    list_code_item_equipment_shoes.append(0x0651);
    //超能跑鞋
    list_code_item_equipment_shoes.append(0x0652);
    //辉光护腿
    list_code_item_equipment_shoes.append(0x0653);
    //缭乱七彩靴
    list_code_item_equipment_shoes.append(0x0654);
    //虚空护腿
    list_code_item_equipment_shoes.append(0x0655);
    //天神战斗靴
    list_code_item_equipment_shoes.append(0x0656);
    //神宠高跟鞋
    list_code_item_equipment_shoes.append(0x0657);
    //金耀翔天鞋
    list_code_item_equipment_shoes.append(0x0658);
    //银耀星影鞋
    list_code_item_equipment_shoes.append(0x0659);
    //斯托雷加Ω
    list_code_item_equipment_shoes.append(0x065A);

    //珊瑚戒指+
    list_code_item_equipment_jewelry.append(0x001E);
    //英雄戒指+
    list_code_item_equipment_jewelry.append(0x001F);
    //夜光眼镜+
    list_code_item_equipment_jewelry.append(0x0020);
    //凉爽项链+
    list_code_item_equipment_jewelry.append(0x0021);
    //打火机+
    list_code_item_equipment_jewelry.append(0x0022);
    //幻彩围巾+
    list_code_item_equipment_jewelry.append(0x0023);
    //叮当耳环+
    list_code_item_equipment_jewelry.append(0x0024);
    //钢手镯+
    list_code_item_equipment_jewelry.append(0x0025);
    //花之瓶+
    list_code_item_equipment_jewelry.append(0x0026);
    //坚硬肉干
    list_code_item_equipment_jewelry.append(0x0027);
    //海刃奖牌
    list_code_item_equipment_jewelry.append(0x0028);
    //水狂奖牌
    list_code_item_equipment_jewelry.append(0x0029);
    //龙宫奖牌
    list_code_item_equipment_jewelry.append(0x002A);
    //银螭奖牌
    list_code_item_equipment_jewelry.append(0x002B);
    //钓皇奖牌
    list_code_item_equipment_jewelry.append(0x002C);
    //狙击枪管
    list_code_item_equipment_jewelry.append(0x002D);
    //影丸头巾
    list_code_item_equipment_jewelry.append(0x002E);
    //咪西尾巴
    list_code_item_equipment_jewelry.append(0x002F);
    //咪西帽子
    list_code_item_equipment_jewelry.append(0x0030);
    //咪雪爪子
    list_code_item_equipment_jewelry.append(0x0031);
    //咪雪缎带
    list_code_item_equipment_jewelry.append(0x0032);
    //进击刻印
    list_code_item_equipment_jewelry.append(0x0033);
    //超·必胜扎头巾
    list_code_item_equipment_jewelry.append(0x0034);
    //超·斗魂腰带
    list_code_item_equipment_jewelry.append(0x0035);
    //正义徽章
    list_code_item_equipment_jewelry.append(0x0036);
    //幸运刻印
    list_code_item_equipment_jewelry.append(0x0037);
    //光晓之冠
    list_code_item_equipment_jewelry.append(0x0038);
    //盘古之冠
    list_code_item_equipment_jewelry.append(0x0039);
    //馥郁香波
    list_code_item_equipment_jewelry.append(0x003A);
    //银胸针
    list_code_item_equipment_jewelry.append(0x003C);
    //珊瑚戒指
    list_code_item_equipment_jewelry.append(0x003D);
    //英雄戒指
    list_code_item_equipment_jewelry.append(0x003E);
    //夜光眼镜
    list_code_item_equipment_jewelry.append(0x003F);
    //凉爽项链
    list_code_item_equipment_jewelry.append(0x0040);
    //打火机
    list_code_item_equipment_jewelry.append(0x0041);
    //幻彩围巾
    list_code_item_equipment_jewelry.append(0x0042);
    //叮当耳环
    list_code_item_equipment_jewelry.append(0x0043);
    //钢手镯
    list_code_item_equipment_jewelry.append(0x0044);
    //花之瓶
    list_code_item_equipment_jewelry.append(0x0045);
    //神圣之链
    list_code_item_equipment_jewelry.append(0x0046);
    //云之使者
    list_code_item_equipment_jewelry.append(0x0047);
    //月亮灵摆
    list_code_item_equipment_jewelry.append(0x0048);
    //太阳灵摆
    list_code_item_equipment_jewelry.append(0x0049);
    //星辰灵摆
    list_code_item_equipment_jewelry.append(0x004A);
    //加长枪管
    list_code_item_equipment_jewelry.append(0x004B);
    //规律徽章
    list_code_item_equipment_jewelry.append(0x004C);
    //勇气徽章
    list_code_item_equipment_jewelry.append(0x004D);
    //闪光徽章
    list_code_item_equipment_jewelry.append(0x004E);
    //必胜扎头巾
    list_code_item_equipment_jewelry.append(0x004F);
    //斗魂腰带
    list_code_item_equipment_jewelry.append(0x0050);
    //星杯挂坠
    list_code_item_equipment_jewelry.append(0x0051);
    //银之链
    list_code_item_equipment_jewelry.append(0x0052);
    //月灵玉
    list_code_item_equipment_jewelry.append(0x0053);
    //咪雪挂饰
    list_code_item_equipment_jewelry.append(0x0054);
    //土人偶
    list_code_item_equipment_jewelry.append(0x0055);
    //寂静之蓝
    list_code_item_equipment_jewelry.append(0x0056);
    //激情之红
    list_code_item_equipment_jewelry.append(0x0057);
    //常青之绿
    list_code_item_equipment_jewelry.append(0x0058);
    //深邃之黄
    list_code_item_equipment_jewelry.append(0x0059);
    //草帽
    list_code_item_equipment_jewelry.append(0x005A);
    //安全头盔
    list_code_item_equipment_jewelry.append(0x005B);
    //医用手套
    list_code_item_equipment_jewelry.append(0x005C);
    //睡猫硬币
    list_code_item_equipment_jewelry.append(0x005E);
    //跳蛙硬币
    list_code_item_equipment_jewelry.append(0x005F);
    //神圣挂坠
    list_code_item_equipment_jewelry.append(0x0061);
    //五彩风车
    list_code_item_equipment_jewelry.append(0x0063);

    //翠耀石挂饰
    list_code_item_equipment_jewelry.append(0x0398);
    //苍耀石挂饰
    list_code_item_equipment_jewelry.append(0x0399);
    //红耀石挂饰
    list_code_item_equipment_jewelry.append(0x039A);
    //琥耀石挂饰
    list_code_item_equipment_jewelry.append(0x039B);
    //金耀石挂饰
    list_code_item_equipment_jewelry.append(0x039C);
    //修利的帽子
    list_code_item_equipment_jewelry.append(0x039D);
    //芙兰的护符
    list_code_item_equipment_jewelry.append(0x039E);
    //舞姬的发饰
    list_code_item_equipment_jewelry.append(0x039F);
    //勇士之心
    list_code_item_equipment_jewelry.append(0x03A0);
    //零之神珠
    list_code_item_equipment_jewelry.append(0x03A1);

    //HP1
    list_code_item_circuit_normal.append(0x0064);
    //HP2
    list_code_item_circuit_normal.append(0x0065);
    //HP3
    list_code_item_circuit_normal.append(0x0066);
    //水耀珠
    list_code_item_circuit_normal.append(0x0067);
    //EP1
    list_code_item_circuit_normal.append(0x0068);
    //EP2
    list_code_item_circuit_normal.append(0x0069);
    //EP3
    list_code_item_circuit_normal.append(0x006A);
    //银耀珠
    list_code_item_circuit_normal.append(0x006B);
    //攻击1
    list_code_item_circuit_normal.append(0x006C);
    //攻击2
    list_code_item_circuit_normal.append(0x006D);
    //攻击3
    list_code_item_circuit_normal.append(0x006E);
    //红耀珠
    list_code_item_circuit_normal.append(0x006F);
    //防御1
    list_code_item_circuit_normal.append(0x0070);
    //防御2
    list_code_item_circuit_normal.append(0x0071);
    //防御3
    list_code_item_circuit_normal.append(0x0072);
    //琥耀珠
    list_code_item_circuit_normal.append(0x0073);
    //精神1
    list_code_item_circuit_normal.append(0x0074);
    //精神2
    list_code_item_circuit_normal.append(0x0075);
    //精神3
    list_code_item_circuit_normal.append(0x0076);
    //白耀珠
    list_code_item_circuit_normal.append(0x0077);
    //魔防1
    list_code_item_circuit_normal.append(0x0078);
    //魔防2
    list_code_item_circuit_normal.append(0x0079);
    //魔防3
    list_code_item_circuit_normal.append(0x007A);
    //苍耀珠
    list_code_item_circuit_normal.append(0x007B);
    //命中1
    list_code_item_circuit_normal.append(0x007C);
    //命中2
    list_code_item_circuit_normal.append(0x007D);
    //命中3
    list_code_item_circuit_normal.append(0x007E);
    //光耀珠
    list_code_item_circuit_normal.append(0x007F);
    //回避1
    list_code_item_circuit_normal.append(0x0080);
    //回避2
    list_code_item_circuit_normal.append(0x0081);
    //回避3
    list_code_item_circuit_normal.append(0x0082);
    //翠耀珠
    list_code_item_circuit_normal.append(0x0083);
    //移动1
    list_code_item_circuit_normal.append(0x0084);
    //移动2
    list_code_item_circuit_normal.append(0x0085);
    //风耀珠
    list_code_item_circuit_normal.append(0x0086);
    //行动力1
    list_code_item_circuit_normal.append(0x0088);
    //行动力2
    list_code_item_circuit_normal.append(0x0089);
    //行动力3
    list_code_item_circuit_normal.append(0x008A);
    //黑耀珠
    list_code_item_circuit_normal.append(0x008B);
    //妨害1
    list_code_item_circuit_normal.append(0x008C);
    //妨害2
    list_code_item_circuit_normal.append(0x008D);
    //绝耀珠
    list_code_item_circuit_normal.append(0x008E);
    //驱动1
    list_code_item_circuit_normal.append(0x008F);
    //驱动2
    list_code_item_circuit_normal.append(0x0090);
    //刻耀珠
    list_code_item_circuit_normal.append(0x0091);
    //省EP1
    list_code_item_circuit_normal.append(0x0092);
    //省EP2
    list_code_item_circuit_normal.append(0x0093);
    //省EP3
    list_code_item_circuit_normal.append(0x0094);
    //金耀珠
    list_code_item_circuit_normal.append(0x0095);

    //毒之刃
    list_code_item_circuit_normal.append(0x0096);
    //石化之刃
    list_code_item_circuit_normal.append(0x0097);
    //封魔之刃
    list_code_item_circuit_normal.append(0x0098);
    //冻结之刃
    list_code_item_circuit_normal.append(0x0099);
    //封技之刃
    list_code_item_circuit_normal.append(0x009A);
    //炎伤之刃
    list_code_item_circuit_normal.append(0x009B);
    //暗之刃
    list_code_item_circuit_normal.append(0x009C);
    //睡眠之刃
    list_code_item_circuit_normal.append(0x009D);
    //混乱之刃
    list_code_item_circuit_normal.append(0x009E);
    //毒之刃2
    list_code_item_circuit_normal.append(0x00BE);
    //石化之刃2
    list_code_item_circuit_normal.append(0x00BF);
    //封魔之刃2
    list_code_item_circuit_normal.append(0x00C0);
    //冻结之刃2
    list_code_item_circuit_normal.append(0x00C1);
    //封技之刃2
    list_code_item_circuit_normal.append(0x00C2);
    //炎伤之刃2
    list_code_item_circuit_normal.append(0x00C3);
    //暗之刃2
    list_code_item_circuit_normal.append(0x00C4);
    //睡眠之刃2
    list_code_item_circuit_normal.append(0x00C5);
    //混乱之刃2
    list_code_item_circuit_normal.append(0x00C6);

    //破剑之牙
    list_code_item_circuit_normal.append(0x009F);
    //破盾之牙
    list_code_item_circuit_normal.append(0x00A0);
    //破言之牙
    list_code_item_circuit_normal.append(0x00A1);
    //破灵之牙
    list_code_item_circuit_normal.append(0x00A2);
    //破迅之牙
    list_code_item_circuit_normal.append(0x00A3);
    //破脚之牙
    list_code_item_circuit_normal.append(0x00A4);

    //镇星铃
    list_code_item_circuit_normal.append(0x00A5);
    //辰星铃
    list_code_item_circuit_normal.append(0x00A6);
    //焰星铃
    list_code_item_circuit_normal.append(0x00A7);
    //岁星铃
    list_code_item_circuit_normal.append(0x00A8);
    //冥王铃
    list_code_item_circuit_normal.append(0x00A9);
    //天王铃
    list_code_item_circuit_normal.append(0x00AA);
    //明王铃
    list_code_item_circuit_normal.append(0x00AB);

    //耀脉
    list_code_item_circuit_normal.append(0x00AC);
    //机功
    list_code_item_circuit_normal.append(0x00AD);
    //虎威
    list_code_item_circuit_normal.append(0x00B4);
    //治愈
    list_code_item_circuit_normal.append(0x00AE);
    //丹精
    list_code_item_circuit_normal.append(0x00AF);
    //炼气
    list_code_item_circuit_normal.append(0x00B0);
    //龙眼
    list_code_item_circuit_normal.append(0x00B1);
    //恶戏
    list_code_item_circuit_normal.append(0x00B2);
    //脱兔
    list_code_item_circuit_normal.append(0x00B3);
    //美臭
    list_code_item_circuit_normal.append(0x00B5);
    //幸运
    list_code_item_circuit_normal.append(0x00B6);
    //缚魔
    list_code_item_circuit_normal.append(0x00BC);
    //鹰目
    list_code_item_circuit_normal.append(0x00B7);
    //天眼
    list_code_item_circuit_normal.append(0x00B8);
    //范围
    list_code_item_circuit_normal.append(0x00B9);
    //情报
    list_code_item_circuit_normal.append(0x00BA);
    //探知
    list_code_item_circuit_normal.append(0x00BB);
    //幻胧
    list_code_item_circuit_normal.append(0x00BD);

    //力量
    list_code_item_circuit_core.append(0x00DC);
    //盾牌
    list_code_item_circuit_core.append(0x00DD);
    //妖精
    list_code_item_circuit_core.append(0x00DE);
    //利爪
    list_code_item_circuit_core.append(0x00DF);
    //白金
    list_code_item_circuit_core.append(0x00E0);
    //幻象
    list_code_item_circuit_core.append(0x00E1);
    //战斧
    list_code_item_circuit_core.append(0x00E2);
    //法则
    list_code_item_circuit_core.append(0x00E3);
    //羽翼
    list_code_item_circuit_core.append(0x00E4);
    //神佑
    list_code_item_circuit_core.append(0x00E5);
    //王权
    list_code_item_circuit_core.append(0x00E6);
    //魅影
    list_code_item_circuit_core.append(0x00E7);
    //守护
    list_code_item_circuit_core.append(0x00E8);
    //无限
    list_code_item_circuit_core.append(0x00E9);
    //小丑
    list_code_item_circuit_core.append(0x00EA);
    //罪恶
    list_code_item_circuit_core.append(0x00EB);
    //草薤
    list_code_item_circuit_core.append(0x00EC);
    //纹章
    list_code_item_circuit_core.append(0x00ED);
    //灵猫
    list_code_item_circuit_core.append(0x00EE);
    //骑士
    list_code_item_circuit_core.append(0x00EF);
    //贤者
    list_code_item_circuit_core.append(0x00F0);
    //草薤
    list_code_item_circuit_core.append(0x00F1);

    //-----
    list_code_item_circuit_debug.append(0x0087);
    //物理吸收
    list_code_item_circuit_debug.append(0x00CB);
    //魔法吸收
    list_code_item_circuit_debug.append(0x00CC);
    //物理反射
    list_code_item_circuit_debug.append(0x00CD);
    //魔法反射
    list_code_item_circuit_debug.append(0x00CE);
    //100%毒之刃
    list_code_item_circuit_debug.append(0x00CF);
    //100%石化之刃
    list_code_item_circuit_debug.append(0x00D0);
    //100%封魔之刃
    list_code_item_circuit_debug.append(0x00D1);
    //100%冻结之刃
    list_code_item_circuit_debug.append(0x00D2);
    //100%封技之刃
    list_code_item_circuit_debug.append(0x00D3);
    //100%炎伤之刃
    list_code_item_circuit_debug.append(0x00D4);
    //100%黑暗之刃
    list_code_item_circuit_debug.append(0x00D5);
    //100%睡眠之刃
    list_code_item_circuit_debug.append(0x00D6);
    //100%混乱之刃
    list_code_item_circuit_debug.append(0x00D7);
    //100%即死之刃
    list_code_item_circuit_debug.append(0x00D8);

    //受损的警察徽章
    list_code_item_event_story.append(0x0320);
    //伊梅尔达馆的钥匙
    list_code_item_event_story.append(0x0321);
    //地下空间B区域的钥匙
    list_code_item_event_story.append(0x0322);
    //旧矿山的钥匙
    list_code_item_event_story.append(0x0323);
    //lBC认证卡片
    list_code_item_event_story.append(0x0324);
    //梅琳的伞
    list_code_item_event_story.append(0x0325);
    //IBC贵宾卡片
    list_code_item_event_story.append(0x0326);
    //废弃材料
    list_code_item_event_story.append(0x0328);
    //纯白之石[大]
    list_code_item_event_story.append(0x032C);
    //纯白之石[中]
    list_code_item_event_story.append(0x0329);
    //纯白之石[小]
    list_code_item_event_story.append(0x032B);
    //尼克鲁的问诊表
    list_code_item_event_story.append(0x032D);
    //迪诺的问诊表
    list_code_item_event_story.append(0x032E);
    //库雷斯队员的问诊表
    list_code_item_event_story.append(0x032F);
    //沉重货物
    list_code_item_event_story.append(0x0330);
    //易碎品的小包裹
    list_code_item_event_story.append(0x0331);
    //发往住宅街的送货单
    list_code_item_event_story.append(0x0332);
    //蓝花
    list_code_item_event_story.append(0x0333);
    //结晶碎片
    list_code_item_event_story.append(0x0334);
    //罗赞贝尔克人偶．C
    list_code_item_event_story.append(0x0335);
    //罗赞贝尔克人偶．R
    list_code_item_event_story.append(0x0336);
    //罗赞贝尔克人偶．M
    list_code_item_event_story.append(0x0337);
    //罗赞贝尔克人偶．S
    list_code_item_event_story.append(0x0338);
    //波波碰！β版
    list_code_item_event_story.append(0x0339);
    //小箱子
    list_code_item_event_story.append(0x033A);
    //月之宝珠
    list_code_item_event_story.append(0x033E);
    //星之光玉
    list_code_item_event_story.append(0x033F);
    //苦西红柿酱
    list_code_item_event_story.append(0x0340);
    //选秀活动特别奖纪念盾[艾莉]
    list_code_item_event_story.append(0x0341);
    //选秀活动特别奖纪念盾[提欧]
    list_code_item_event_story.append(0x0342);
    //选秀活动特别奖纪念盾[诺埃尔]
    list_code_item_event_story.append(0x0343);
    //绀碧竿
    list_code_item_event_story.append(0x0344);
    //琥珀轴
    list_code_item_event_story.append(0x0345);
    //翡翠线
    list_code_item_event_story.append(0x0346);
    //红莲钩
    list_code_item_event_story.append(0x0347);
    //支援科车辆钥匙
    list_code_item_event_story.append(0x035C);
    //米修拉姆·奇幻乐园游乐券
    list_code_item_event_story.append(0x035D);
    //临时认证卡片
    list_code_item_event_story.append(0x035E);
    //金属探测器
    list_code_item_event_story.append(0x0375);
    //银耀石钥匙
    list_code_item_event_story.append(0x0376);
    //金耀石钥匙
    list_code_item_event_story.append(0x0377);
    //黑耀石钥匙
    list_code_item_event_story.append(0x0378);
    //红色卡片钥匙
    list_code_item_event_story.append(0x0379);
    //U材料
    list_code_item_event_story.append(0x038E);
    //塞姆里亚石碎片
    list_code_item_event_story.append(0x0394);
    //神圣布料
    list_code_item_event_story.append(0x0395);
    //塞姆里亚石
    list_code_item_event_story.append(0x0396);

    //迷你沙袋
    list_code_item_event_furnishing.append(0x0348);
    //特里斯坦号
    list_code_item_event_furnishing.append(0x0349);
    //优雅衣镜
    list_code_item_event_furnishing.append(0x034A);
    //八音盒
    list_code_item_event_furnishing.append(0x034B);
    //影丸储蓄罐
    list_code_item_event_furnishing.append(0x034C);
    //咪雪玩偶
    list_code_item_event_furnishing.append(0x034D);
    //冲浪板
    list_code_item_event_furnishing.append(0x034E);
    //点唱机
    list_code_item_event_furnishing.append(0x034F);
    //竞赛旗
    list_code_item_event_furnishing.append(0x0350);
    //小径自行车
    list_code_item_event_furnishing.append(0x0351);
    //安乐椅
    list_code_item_event_furnishing.append(0x0352);
    //迷你水族馆
    list_code_item_event_furnishing.append(0x0353);
    //古怪靠垫
    list_code_item_event_furnishing.append(0x0354);
    //波波靠垫
    list_code_item_event_furnishing.append(0x0355);
    //黑泰迪熊
    list_code_item_event_furnishing.append(0x0356);
    //苦番茄人玩偶
    list_code_item_event_furnishing.append(0x0357);
    //ZWEI2企鹅
    list_code_item_event_furnishing.append(0x0358);

    //挡泥板
    list_code_item_event_car.append(0x035F);
    //侧踏板
    list_code_item_event_car.append(0x0360);
    //尾翼
    list_code_item_event_car.append(0x0361);
    //前保险杠
    list_code_item_event_car.append(0x0362);
    //警灯
    list_code_item_event_car.append(0x0363);
    //强化轮圈
    list_code_item_event_car.append(0x0364);
    //HP回复装置
    list_code_item_event_car.append(0x0365);
    //EP回复装置
    list_code_item_event_car.append(0x0366);
    //CP回复装置
    list_code_item_event_car.append(0x0367);
    //CPD主题
    list_code_item_event_car.append(0x0368);
    //咪西主题
    list_code_item_event_car.append(0x0369);
    //人物主题E
    list_code_item_event_car.append(0x036A);
    //人物主题T
    list_code_item_event_car.append(0x036B);
    //天空色彩
    list_code_item_event_car.append(0x036C);
    //高贵色彩
    list_code_item_event_car.append(0x036D);
    //魅力色彩
    list_code_item_event_car.append(0x036E);
    //狂野色彩
    list_code_item_event_car.append(0x036F);
    //凉爽色彩
    list_code_item_event_car.append(0x0370);
    //警备色彩
    list_code_item_event_car.append(0x0371);
    //轻快色彩
    list_code_item_event_car.append(0x0372);
    //闪耀色彩
    list_code_item_event_car.append(0x0373);
    //深暗色彩
    list_code_item_event_car.append(0x0374);

    //魔兽兽肉
    list_code_item_food.append(0x012C);
    //魔兽鱼肉
    list_code_item_food.append(0x012D);
    //魔兽之壳
    list_code_item_food.append(0x012E);
    //魔兽之卵
    list_code_item_food.append(0x012F);
    //魔兽羽翼
    list_code_item_food.append(0x0130);
    //魔兽之种
    list_code_item_food.append(0x0131);
    //魔兽明胶
    list_code_item_food.append(0x0132);
    //发芽糙米
    list_code_item_food.append(0x0134);
    //五谷味增
    list_code_item_food.append(0x0135);
    //百药精酒
    list_code_item_food.append(0x0136);
    //朝摘香叶
    list_code_item_food.append(0x0137);
    //清绿香草
    list_code_item_food.append(0x0138);
    //胡椒粒
    list_code_item_food.append(0x0139);
    //热辣椒
    list_code_item_food.append(0x013A);
    //香油
    list_code_item_food.append(0x013B);
    //蜂蜜糖浆
    list_code_item_food.append(0x013C);
    //粗碎岩盐
    list_code_item_food.append(0x013D);
    //新磨小麦粉
    list_code_item_food.append(0x013E);
    //新鲜牛奶
    list_code_item_food.append(0x013F);
    //新鲜奶酪
    list_code_item_food.append(0x0140);
    //新鲜鸡蛋
    list_code_item_food.append(0x0141);
    //铃铛草莓
    list_code_item_food.append(0x0142);
    //黑暗菇
    list_code_item_food.append(0x0143);
    //七彩豆
    list_code_item_food.append(0x0144);
    //国王马铃薯
    list_code_item_food.append(0x0145);
    //万能青葱
    list_code_item_food.append(0x0146);
    //迷你胡萝卜
    list_code_item_food.append(0x0147);
    //苦西红柿
    list_code_item_food.append(0x0148);
    //雪花里脊肉
    list_code_item_food.append(0x0149);
    //新鲜白鱼肉
    list_code_item_food.append(0x014A);


    //调查手册
    list_code_item_book.append(0x0001);
    //料理手册
    list_code_item_book.append(0x0002);
    //钓鱼手册
    list_code_item_book.append(0x0003);
    //战斗手册
    list_code_item_book.append(0x0004);
    //自治州地图
    list_code_item_book.append(0x0005);
    //克洛斯贝尔市的地图
    list_code_item_book.append(0x0006);
    //战术书·击
    list_code_item_book.append(0x000a);
    //战术书·十
    list_code_item_book.append(0x000b);
    //战术书·苍
    list_code_item_book.append(0x000c);
    //战术书·袭
    list_code_item_book.append(0x000d);
    //战术书·虚
    list_code_item_book.append(0x000e);
    //战术书·爆
    list_code_item_book.append(0x000f);
    //战术书·里
    list_code_item_book.append(0x0010);
    //战术书·升
    list_code_item_book.append(0x0011);
    //克洛斯贝尔时代周刊①
    list_code_item_book.append(0x02bc);
    //克洛斯贝尔时代周刊②
    list_code_item_book.append(0x02bd);
    //克洛斯贝尔时代周刊③
    list_code_item_book.append(0x02be);
    //克洛斯贝尔时代周刊号外
    list_code_item_book.append(0x02bf);
    //克洛斯贝尔时代周刊④
    list_code_item_book.append(0x02c0);
    //克洛斯贝尔时代周刊⑤
    list_code_item_book.append(0x02c1);
    //克洛斯贝尔时代周刊⑥
    list_code_item_book.append(0x02c2);
    //克洛斯贝尔时代周刊⑦
    list_code_item_book.append(0x02c3);
    //克洛斯贝尔时代周刊⑧
    list_code_item_book.append(0x02c4);
    //黑市医生格伦 1卷
    list_code_item_book.append(0x02C6);
    //黑市医生格伦 2卷
    list_code_item_book.append(0x02C7);
    //黑市医生格伦 3卷
    list_code_item_book.append(0x02C8);
    //黑市医生格伦 4卷
    list_code_item_book.append(0x02C9);
    //黑市医生格伦 5卷
    list_code_item_book.append(0x02CA);
    //黑市医生格伦 6卷
    list_code_item_book.append(0x02CB);
    //黑市医生格伦 7卷
    list_code_item_book.append(0x02CC);
    //黑市医生格伦 8卷
    list_code_item_book.append(0x02CD);
    //黑市医生格伦 9卷
    list_code_item_book.append(0x02CE);
    //黑市医生格伦 10卷
    list_code_item_book.append(0x02Cf);
    //黑市医生格伦 11卷
    list_code_item_book.append(0x02D0);
    //黑市医生格伦 12卷
    list_code_item_book.append(0x02D1);
    //黑市医生格伦 13卷
    list_code_item_book.append(0x02D2);
    //黑市医生格伦 14卷
    list_code_item_book.append(0x02D3);
    //铁道爱好者的推荐
    list_code_item_book.append(0x02D5);
    //玛尔克与森林深处的魔女们·上
    list_code_item_book.append(0x02D6);
    //玛尔克与森林深处的魔女们·中
    list_code_item_book.append(0x02DD);
    //玛尔克与森林深处的魔女们·下
    list_code_item_book.append(0x02DE);
    //改变大陆的美人们
    list_code_item_book.append(0x02D7);
    //有效利用五分钟零散时间
    list_code_item_book.append(0x02D8);
    //克洛斯贝尔怪谈全集
    list_code_item_book.append(0x02D9);
    //彩虹·Funbook
    list_code_item_book.append(0x02DA);
    //圣女与白狼·上
    list_code_item_book.append(0x02DF);
    //圣女与白狼·下
    list_code_item_book.append(0x02E0);
    //克洛斯贝尔时代周刊⑴
    list_code_item_book.append(0x02E1);
    //克洛斯贝尔时代周刊⑵
    list_code_item_book.append(0x02E2);
    //克洛斯贝尔时代周刊⑶
    list_code_item_book.append(0x02E3);
    //克洛斯贝尔时代周刊⑷
    list_code_item_book.append(0x02E4);
    //克洛斯贝尔时代周刊⑸
    list_code_item_book.append(0x02E5);
    //克洛斯贝尔时代周刊⑹
    list_code_item_book.append(0x02E6);
    //克洛斯贝尔时代周刊⑺
    list_code_item_book.append(0x02E7);
    //克洛斯贝尔时代周刊⑻
    list_code_item_book.append(0x02E8);
    //克洛斯贝尔时代周刊⑨
    list_code_item_book.append(0x02E9);
    //克洛斯贝尔时代周刊号外
    list_code_item_book.append(0x02EA);
    //克洛斯贝尔时代周刊⑽
    list_code_item_book.append(0x02EB);
    //克洛斯贝尔时代周刊⑾
    list_code_item_book.append(0x02EC);
    //沐浴阳光的阿尼艾斯 1卷
    list_code_item_book.append(0x02EE);
    //沐浴阳光的阿尼艾斯 2卷
    list_code_item_book.append(0x02EF);
    //沐浴阳光的阿尼艾斯 3卷
    list_code_item_book.append(0x02F0);
    //沐浴阳光的阿尼艾斯 4卷
    list_code_item_book.append(0x02F1);
    //沐浴阳光的阿尼艾斯 5卷
    list_code_item_book.append(0x02F2);
    //沐浴阳光的阿尼艾斯 6卷
    list_code_item_book.append(0x02F3);
    //沐浴阳光的阿尼艾斯 7卷
    list_code_item_book.append(0x02F4);
    //沐浴阳光的阿尼艾斯 8卷
    list_code_item_book.append(0x02F5);
    //沐浴阳光的阿尼艾斯 9卷
    list_code_item_book.append(0x02F6);
    //沐浴阳光的阿尼艾斯 10卷
    list_code_item_book.append(0x02F7);
    //沐浴阳光的阿尼艾斯 11卷
    list_code_item_book.append(0x02F8);
    //沐浴阳光的阿尼艾斯 12卷
    list_code_item_book.append(0x02F9);
    //沐浴阳光的阿尼艾斯 13卷
    list_code_item_book.append(0x02FA);
    //沐浴阳光的阿尼艾斯 14卷
    list_code_item_book.append(0x02FB);
    //幻兽调查报告书
    list_code_item_book.append(0x02FC);


    //鲑鱼卵
    list_code_item_fishing_bait.append(0x0186);
    //熬炼丸子
    list_code_item_fishing_bait.append(0x0187);
    //红虫
    list_code_item_fishing_bait.append(0x0188);
    //蚯蚓
    list_code_item_fishing_bait.append(0x0189);
    //熬炼丸子DX
    list_code_item_fishing_bait.append(0x018a);
    //虹丸EX
    list_code_item_fishing_bait.append(0x018b);
    //垂钓大礼包
    list_code_item_fishing_bait.append(0x018c);

    //斗鱼
    list_code_item_fishing_fish.append(0x015E);
    //雪花蟹
    list_code_item_fishing_fish.append(0x015F);
    //蓝带神仙鱼
    list_code_item_fishing_fish.append(0x0160);
    //银伞鱼
    list_code_item_fishing_fish.append(0x0161);
    //阿尔摩里卡鲫鱼
    list_code_item_fishing_fish.append(0x0162);
    //乌龟
    list_code_item_fishing_fish.append(0x0163);
    //橙河鱼
    list_code_item_fishing_fish.append(0x0164);
    //岩穴鱼
    list_code_item_fishing_fish.append(0x0165);
    //虹鳟鱼
    list_code_item_fishing_fish.append(0x0166);
    //食人鱼
    list_code_item_fishing_fish.append(0x0167);
    //鲤鱼
    list_code_item_fishing_fish.append(0x0168);
    //大口鲈鱼
    list_code_item_fishing_fish.append(0x0169);
    //黑鲑
    list_code_item_fishing_fish.append(0x016A);
    //角斗鱼
    list_code_item_fishing_fish.append(0x016B);
    //冷水鱼
    list_code_item_fishing_fish.append(0x016C);
    //小鲵
    list_code_item_fishing_fish.append(0x016D);
    //鲑鱼
    list_code_item_fishing_fish.append(0x016E);
    //金龙鱼
    list_code_item_fishing_fish.append(0x016F);
    //鳗鲡
    list_code_item_fishing_fish.append(0x0170);
    //钢壳龟
    list_code_item_fishing_fish.append(0x0171);
    //巨血蟹
    list_code_item_fishing_fish.append(0x0172);
    //珍珠龙鱼
    list_code_item_fishing_fish.append(0x0173);
    //巨鲶
    list_code_item_fishing_fish.append(0x0174);
    //金鲑
    list_code_item_fishing_fish.append(0x0175);
    //大鲵
    list_code_item_fishing_fish.append(0x0176);
    //锦鲤
    list_code_item_fishing_fish.append(0x0177);
    //翠耀神仙鱼
    list_code_item_fishing_fish.append(0x0178);
    //琥耀岩穴鱼
    list_code_item_fishing_fish.append(0x0179);
    //红耀食人鱼
    list_code_item_fishing_fish.append(0x017A);
    //苍耀巨龙鱼
    list_code_item_fishing_fish.append(0x017B);
    //巨骨龙鱼皇
    list_code_item_fishing_fish.append(0x017C);

    //初级杆
    list_code_item_fishing_rod.append(0x0014);
    //小巧射手
    list_code_item_fishing_rod.append(0x0015);
    //竹竿
    list_code_item_fishing_rod.append(0x0016);
    //钢竿侵略者
    list_code_item_fishing_rod.append(0x0017);
    //水中支配者
    list_code_item_fishing_rod.append(0x0018);
}

#endif // BZH_ANK_SE_CODE_DEFINE_ITEM_H
